// Shadow Casters — English translations. Keys are the Spanish texts used in
// the interface (see i18n.js). Missing keys fall back to Spanish.

export const EN = {
  // --- editor: canvas, stage, layers
  '● guardando…': '● saving…',
  'No hay nada para deshacer': 'Nothing to undo',
  'Pieza': 'Piece',
  'Seleccionada:': 'Selected:',
  'Hacé clic en una capa para editarla · arrastrá el fondo para moverte': 'Click a layer to edit it · drag the background to pan',
  'Listo: ese color se quita como fondo. Ajustá la tolerancia si hace falta.': 'Done: that color is removed as background. Adjust the tolerance if needed.',
  'Hacé clic dentro de la foto, sobre el color del fondo': 'Click inside the photo, on the background color',
  'Soltá una imagen (jpg, png, gif, webp…)': 'Drop an image (jpg, png, gif, webp…)',
  'ESPEJADA (vinilo termoadhesivo)': 'MIRRORED (iron-on vinyl)',
  'dibujo': 'drawing',
  'todavía no hay nada dibujado': 'nothing drawn yet',
  'Movés el mouse por acá y se mueve la luz 🔦': 'Move the mouse here to move the light 🔦',
  'Sombra proyectada de': 'Projected shadow of',
  'tu pieza': 'your piece',
  'Tapete 12 × 12"': '12 × 12" mat',
  'en el tapete': 'on the mat',
  'espejada': 'mirrored',
  'calculando…': 'calculating…',
  'El corte mide': 'The cut measures',
  'No hay nada para cortar todavía': 'Nothing to cut yet',
  '¡Todo bien! Una sola pieza, sin detalles demasiado finos. Lista para cortar.': 'All good! One single piece, no details too thin. Ready to cut.',
  'La pieza: ajustala con los bloques naranjas': 'The piece: adjust it with the orange blocks',
  'Ninguna capa seleccionada': 'No layer selected',
  'Acá van a aparecer tus capas: cada imagen, texto o forma que agregues.': 'Your layers will show up here: every image, text or shape you add.',
  'Resta (agujero). Clic para sumar': 'Subtract (hole). Click to add',
  'Suma (figura). Clic para restar': 'Add (figure). Click to subtract',
  'Eliminar': 'Delete',
  'Texto': 'Text',
  'HOLA': 'HELLO',
  'Puente': 'Bridge',
  'Leyendo la imagen…': 'Reading the image…',
  'Foto': 'Photo',
  '¡Imagen agregada! Si quedó mal el fondo, ajustalo con los bloques violetas.': 'Image added! If the background looks wrong, fix it with the purple blocks.',
  'El fondo automático borraba toda la foto: la dejé entera. Usá el gotero sobre el fondo o «sólo lo oscuro».': 'Automatic background removal erased the whole photo, so I kept it whole. Use the eyedropper on the background or “only the dark parts”.',
  'No encontré un fondo liso: la foto queda entera. Usá el gotero sobre el fondo o «sólo lo oscuro».': 'No plain background found: the photo stays whole. Use the eyedropper on the background or “only the dark parts”.',
  'No se pudo cargar la imagen': 'Could not load the image',
  'copia': 'copy',
  '{n} capa': '{n} layer',
  '{n} capas': '{n} layers',
  '{n} pieza': '{n} piece',
  '{n} piezas': '{n} pieces',

  // --- palette: images
  'Imágenes': 'Images',
  'Fotos o dibujos. Les sacamos el fondo y quedan como silueta negra.': 'Photos or drawings. We remove the background and they become a black silhouette.',
  'subir una imagen': 'upload an image',
  'Elegí una foto o dibujo de tu computadora (también podés arrastrarla al lienzo o pegarla con Ctrl+V)': 'Pick a photo or drawing from your computer (you can also drag it onto the canvas or paste it with Ctrl+V)',
  'sacar una foto': 'take a photo',
  'Usa la cámara. Ideal para hacer tu propia silueta.': 'Uses the camera. Perfect for making your own silhouette.',
  'Quitar el fondo': 'Remove the background',
  'Seleccioná una imagen en el lienzo para usar estos bloques.': 'Select an image on the canvas to use these blocks.',
  'No quedó casi nada. Bajá la tolerancia, o elegí «no quitar nada» y «sólo lo oscuro».': 'Almost nothing is left. Lower the tolerance, or choose “remove nothing” and “only the dark parts”.',
  'Quedó toda la foto como un bloque. Subí la tolerancia, usá el gotero sobre el fondo, o «sólo lo oscuro» si es un dibujo.': 'The whole photo became one block. Raise the tolerance, use the eyedropper on the background, or “only the dark parts” if it is a drawing.',
  '<b>{pct} %</b> de la imagen queda como figura.': '<b>{pct} %</b> of the image becomes figure.',
  'quitar el fondo': 'remove background',
  'automático (desde los bordes)': 'automatic (from the edges)',
  'de un color que elijo': 'a color I pick',
  'no quitar nada': 'remove nothing',
  'tolerancia': 'tolerance',
  'Cuánto puede variar el color del fondo para que igual se quite': 'How much the background color may vary and still be removed',
  'Pasar a silueta': 'Turn into a silhouette',
  'la figura es': 'the figure is',
  'todo lo que quedó': 'everything that is left',
  'sólo lo oscuro (dibujo a lápiz)': 'only the dark parts (pencil drawing)',
  'sólo lo claro': 'only the light parts',
  'umbral': 'threshold',
  'invertir (negativo)': 'invert (negative)',
  'suavizar': 'smooth',
  'Cierra grietas y redondea': 'Closes cracks and rounds corners',
  'engrosar / afinar': 'thicken / thin',
  '+ engorda, − adelgaza': '+ thicker, − thinner',
  'limpiar manchas': 'clean specks',
  'Borra pedacitos más chicos que esto': 'Erases bits smaller than this',
  'cambiar la imagen': 'change the image',

  // --- palette: text
  'Tu nombre, una palabra, un título. Doble clic en un texto del lienzo para editarlo.': 'Your name, a word, a title. Double-click a text on the canvas to edit it.',
  'agregar un texto': 'add a text',
  'agregar mi nombre': 'add my name',
  'Escribe tu nombre (el de arriba) como texto': 'Writes your name (the one at the top) as text',
  'Seleccioná un texto en el lienzo para cambiarlo.': 'Select a text on the canvas to change it.',
  'dice': 'says',
  'tamaño': 'size',
  'alineación': 'alignment',
  'izquierda': 'left',
  'centro': 'center',
  'derecha': 'right',
  'negrita': 'bold',
  'espacio entre letras': 'letter spacing',
  'Juntarlas hace que queden unidas al cortar': 'Bringing them closer keeps them joined when cut',
  'espacio entre líneas': 'line spacing',
  'Fuente': 'Font',
  'Para que las letras salgan en una sola pieza, elegí una fuente gorda y letras juntas.': 'To get the letters in a single piece, pick a fat font and tight spacing.',

  // --- palette: shapes
  'Formas': 'Shapes',
  'Clic o arrastrá al lienzo. Con «− resta» hacen agujeros; el puente une piezas sueltas.': 'Click or drag onto the canvas. With “− subtract” they make holes; the bridge joins loose pieces.',
  'Esta forma': 'This shape',
  'forma': 'shape',
  'puntas': 'points',
  'radio interior': 'inner radius',
  'esquinas': 'corners',
  'grosor': 'thickness',
  'ancho': 'width',
  'alto': 'height',

  // --- palette: edit
  'Editar': 'Edit',
  'Estos bloques actúan sobre la capa seleccionada.': 'These blocks act on the selected layer.',
  'suma: agrega figura (negro)': 'add: makes figure (black)',
  'resta: hace un agujero (rojo)': 'subtract: makes a hole (red)',
  'Por el agujero pasa la luz': 'Light goes through the hole',
  'centrar en la pieza': 'center on the piece',
  'agrandar hasta llenar la pieza': 'enlarge to fill the piece',
  'espejar (izquierda ↔ derecha)': 'flip (left ↔ right)',
  'voltear (arriba ↔ abajo)': 'flip (up ↔ down)',
  'girar': 'rotate',
  'ir a x:': 'go to x:',
  'y:': 'y:',
  'traer adelante': 'bring forward',
  'mandar atrás': 'send backward',
  'duplicar': 'duplicate',
  'eliminar': 'delete',
  'deshacer': 'undo',
  'rehacer': 'redo',
  'mostrar': 'show',
  'ocultar': 'hide',

  // --- palette: piece
  'La pieza': 'The piece',
  'La hoja donde diseñás: es lo que se corta. Medidas reales, en milímetros.': 'The sheet you design on: this is what gets cut. Real measurements, in millimeters.',
  'tamaño rápido': 'quick size',
  '— elegir —': '— choose —',
  'tipo de pieza': 'piece type',
  'base: ancho': 'base: width',
  'grosor del marco': 'frame thickness',
  'esquinas redondeadas': 'rounded corners',
  'espejar para vinilo termoadhesivo': 'mirror for iron-on vinyl',
  'Se corta al revés y queda bien al plancharlo': 'Cut reversed so it looks right after ironing',
  'ver la sombra en el escenario': 'show the shadow on the stage',
  'ver la pieza en el escenario': 'show the piece on the stage',

  // --- palette: cut & save
  'Cortar': 'Cut',
  'Cortar y guardar': 'Cut and save',
  'El SVG se carga en Cricut Design Space (Upload → Insert → Make It) o en la láser.': 'Load the SVG in Cricut Design Space (Upload → Insert → Make It) or in the laser cutter.',
  'revisar en el tapete': 'check on the mat',
  'Muestra la pieza como la ve la cortadora y avisa si hay piezas sueltas o detalles muy finos': 'Shows the piece as the cutter sees it and warns about loose pieces or very thin details',
  'detalle mínimo': 'minimum detail',
  '1 mm (láser, cartulina)': '1 mm (laser, cardstock)',
  '1,5 mm (vinilo)': '1.5 mm (vinyl)',
  '2,5 mm (vinilo termoadhesivo)': '2.5 mm (iron-on vinyl)',
  'recortar el SVG al dibujo (sin el borde de la hoja)': 'crop the SVG to the drawing (without the sheet border)',
  'descargar SVG para cortar': 'download SVG to cut',
  'descargar PNG (imagen)': 'download PNG (image)',
  'copiar el SVG': 'copy the SVG',
  'Proyecto': 'Project',
  'Se guarda solo en este navegador. Para seguir en otra compu o mandárselo al docente, bajá el .json.': 'It saves itself in this browser. To continue on another computer or send it to your teacher, download the .json.',
  'guardar en mi computadora (.json)': 'save to my computer (.json)',
  'abrir un proyecto (.json)': 'open a project (.json)',
  'empezar de nuevo': 'start over',

  // --- actions / toasts
  'Primero seleccioná una capa en el lienzo (o agregá una)': 'First select a layer on the canvas (or add one)',
  'Ahora hacé clic sobre el fondo de la foto, en el lienzo': 'Now click on the photo background, on the canvas',
  'Gotero cancelado': 'Eyedropper cancelled',
  '¿Cómo te llamás?': 'What is your name?',
  'YO': 'ME',
  'Este navegador no permite usar la cámara.': 'This browser does not allow using the camera.',
  'No pude abrir la cámara: {motivo}. Fijate que el navegador tenga permiso, o subí una foto desde un archivo.': 'Could not open the camera: {motivo}. Check the browser has permission, or upload a photo from a file.',
  'La cámara todavía no arrancó': 'The camera has not started yet',
  '¿Empezar un proyecto nuevo? El de ahora queda guardado en este navegador (y en la clase, si estás en una).': 'Start a new project? The current one stays saved in this browser (and in the class, if you are in one).',
  'Mi sombra': 'My shadow',
  'Proyecto nuevo. ¡A diseñar!': 'New project. Let’s design!',
  'Proyecto guardado en tu computadora. Con ese archivo podés seguir en cualquier otra compu.': 'Project saved to your computer. With that file you can continue on any other computer.',
  'Proyecto abierto: {nombre}': 'Project opened: {nombre}',
  'Ese archivo no es un proyecto válido (.json)': 'That file is not a valid project (.json)',
  'Todavía no hay nada para cortar: agregá una imagen, un texto o una forma': 'Nothing to cut yet: add an image, a text or a shape',
  'SVG descargado. Cargalo en Cricut Design Space → Upload → Insert → Make It': 'SVG downloaded. Load it in Cricut Design Space → Upload → Insert → Make It',
  'PNG descargado (negro sobre blanco)': 'PNG downloaded (black on white)',
  'SVG copiado al portapapeles': 'SVG copied to the clipboard',
  'No se pudo copiar; descargalo con el otro bloque': 'Could not copy; download it with the other block',
  'Seleccioná una capa primero': 'Select a layer first',

  // --- saving / class (student)
  '● guardado en esta compu': '● saved on this computer',
  '● no entra en el navegador: bajá el .json': '● does not fit in the browser: download the .json',
  '● guardado y enviado al docente': '● saved and sent to the teacher',
  '● guardado acá · se envía cuando vuelva la clase': '● saved here · sent when the class is back',
  '● guardado en la clase y enviado al estudiante': '● saved in the class and sent to the student',
  'abierta': 'open',
  'Ver': 'View',
  'Abrir': 'Open',
  'Borrar la clase y sus diseños de este navegador': 'Delete the class and its designs from this browser',
  'sin vista': 'no preview',
  'Sin nombre': 'Untitled',
  'clase': 'class',
  'por mi cuenta': 'on my own',
  'Borrar de esta computadora': 'Delete from this computer',
  '¿Borrar la clase {codigo} y todos sus diseños de este navegador? No se puede deshacer.': 'Delete class {codigo} and all its designs from this browser? This cannot be undone.',
  '¿Borrar este proyecto de esta computadora?': 'Delete this project from this computer?',
  'Mi clase': 'My class',
  '{n} estudiante': '{n} student',
  '{n} estudiantes': '{n} students',
  'El código tiene 6 letras o números. Pedíselo al docente.': 'The code has 6 letters or numbers. Ask your teacher for it.',
  'Escribí tu nombre y apellido: así el docente sabe de quién es cada diseño.': 'Type your first and last name so the teacher knows whose design is whose.',
  'Clase {codigo} · conectando…': 'Class {codigo} · connecting…',
  'Clase {codigo} · conectado': 'Class {codigo} · connected',
  'Clase {codigo} cerrada · seguís trabajando; se envía cuando el docente la abra': 'Class {codigo} closed · keep working; it is sent when the teacher opens it',
  'Clase {codigo} · sin conexión, reintentando…': 'Class {codigo} · offline, retrying…',
  'Te sacaron de la clase': 'You were removed from the class',
  'Clase {codigo} · sin conexión': 'Class {codigo} · offline',
  '¡Hola {nombre}! Tu diseño volvió tal como lo dejaste.': 'Hi {nombre}! Your design is back just as you left it.',
  '¡Hola {nombre}! Estás en la clase «{clase}».': 'Hi {nombre}! You are in the class “{clase}”.',
  'El docente retocó tu diseño: acá está la versión nueva.': 'The teacher touched up your design: here is the new version.',
  'Docente:': 'Teacher:',

  // --- teacher panel
  'No encontré esa clase en este navegador': 'Could not find that class in this browser',
  'Clase {codigo} cerrada. Los diseños quedan guardados en este navegador.': 'Class {codigo} closed. The designs stay saved in this browser.',
  'No hay ninguna clase abierta.': 'No class is open.',
  'Nueva clase': 'New class',
  'Abrir una guardada': 'Open a saved one',
  'Nombre de la clase nueva:': 'Name of the new class:',
  'No hay otras clases guardadas. Creá una nueva.': 'There are no other saved classes. Create a new one.',
  '¿Cuál abrimos? Escribí el código:': 'Which one? Type the code:',
  'abierta: los estudiantes pueden entrar': 'open: students can join',
  'conectando…': 'connecting…',
  'reconectando…': 'reconnecting…',
  'código en uso en otra pestaña': 'code in use in another tab',
  'apagada': 'off',
  'sin conexión': 'offline',
  'Clic para copiar el código': 'Click to copy the code',
  'Código de la clase': 'Class code',
  'Clic para copiar el enlace': 'Click to copy the link',
  'Nombre de la clase': 'Class name',
  '{a} de {b} conectados': '{a} of {b} connected',
  'Dejá esta pestaña abierta: los diseños aparecen abajo a medida que los estudiantes trabajan. Si cerrás la pestaña, ellos siguen diseñando y todo se sincroniza cuando la vuelvas a abrir.': 'Keep this tab open: designs show up below as students work. If you close the tab, they keep designing and everything syncs when you open it again.',
  'Acomoda los diseños marcados en un tapete de 12 × 12 pulgadas y arma un solo SVG': 'Arranges the checked designs on a 12 × 12 inch mat and builds a single SVG',
  'Tapete con los marcados': 'Mat with the checked ones',
  'Marcar todos': 'Check all',
  'Importar .json de un estudiante': 'Import a student’s .json',
  'Exportar la clase (.json)': 'Export the class (.json)',
  'Mensaje para todos (ej.: 5 minutos más)': 'Message to everyone (e.g.: 5 more minutes)',
  'Enviar': 'Send',
  'Cerrar esta clase': 'Close this class',
  'Todavía no entró nadie. Compartí el código (o el enlace) y dejá esta pestaña abierta.': 'Nobody has joined yet. Share the code (or the link) and keep this tab open.',
  'Marcar para el tapete': 'Check for the mat',
  'sin diseño todavía': 'no design yet',
  'en línea': 'online',
  'desconectado': 'offline',
  'actualizado {hora}': 'updated {hora}',
  'sin cambios': 'no changes',
  'Quitar de la clase': 'Remove from the class',
  'Copiado: {texto}': 'Copied: {texto}',
  'Mensaje enviado a {n} estudiantes': 'Message sent to {n} students',
  'Clase exportada': 'Class exported',
  '¿Quitar a {nombre} de la clase? Su diseño se borra de este navegador.': 'Remove {nombre} from the class? Their design is deleted from this browser.',
  'Clase importada': 'Class imported',
  'Importado: {nombre}': 'Imported: {nombre}',
  'No se pudo importar': 'Could not import',
  'Marcá al menos un estudiante con diseño (la casilla de cada tarjeta).': 'Check at least one student with a design (the box on each card).',
  'Armando el tapete…': 'Building the mat…',
  'No entraron en el tapete: {nombres}. Armá otro con ellos.': 'Did not fit on the mat: {nombres}. Build another one with them.',
  'Tapete listo: {n} diseños en un solo SVG': 'Mat ready: {n} designs in a single SVG',
  'Retocando el diseño de {nombre} (clase {codigo})': 'Touching up {nombre}’s design (class {codigo})',
  '↻ {nombre} mandó una versión nueva: cargarla': '↻ {nombre} sent a newer version: load it',
  '{nombre} siguió editando: hay una versión más nueva de su diseño.': '{nombre} kept editing: there is a newer version of their design.',
  'Tus clases siguen abiertas mientras esta pestaña esté abierta.': 'Your classes stay open while this tab is open.',

  // --- network (aula.js)
  'No se cargó PeerJS: la clase sólo funciona con archivos .json.': 'PeerJS did not load: the class only works with .json files.',
  'Falta el nombre.': 'The name is missing.',
  'Entraste desde otra computadora: esta sesión se cerró.': 'You joined from another computer: this session was closed.',
  'Ese código ya está en uso en otra computadora (¿la clase quedó abierta en otra pestaña?).': 'That code is already in use on another computer (is the class open in another tab?).',
  'El docente te quitó de la clase.': 'The teacher removed you from the class.',
  'Este navegador no soporta conexiones directas (WebRTC).': 'This browser does not support direct connections (WebRTC).',
  'No se pudo llegar al servidor de señales (¿la red bloquea la conexión?). Se reintenta solo; mientras tanto se puede trabajar con archivos .json.': 'Could not reach the signaling server (is the network blocking it?). It retries on its own; meanwhile you can work with .json files.',
  'No hay ninguna clase abierta con ese código. Pedile al docente que la abra (tiene que tener la página abierta).': 'There is no open class with that code. Ask the teacher to open it (they need to have the page open).',
  'Error de conexión.': 'Connection error.',
  'No se cargó PeerJS: guardá el .json y mandáselo al docente.': 'PeerJS did not load: save the .json and send it to your teacher.',

  // --- menu bar
  'Archivo ▾': 'File ▾',
  '✨ Nuevo proyecto': '✨ New project',
  '📂 Cargar desde tu computadora (.json)': '📂 Load from your computer (.json)',
  '💾 Guardar en tu computadora (.json)': '💾 Save to your computer (.json)',
  '✂ Descargar SVG para cortar': '✂ Download SVG to cut',
  '🖼 Descargar PNG': '🖼 Download PNG',
  'Editar ▾': 'Edit ▾',
  '↶ Deshacer': '↶ Undo',
  '↷ Rehacer': '↷ Redo',
  '⧉ Duplicar capa': '⧉ Duplicate layer',
  '🗑 Eliminar capa': '🗑 Delete layer',
  '💡 Tutorial': '💡 Tutorial',
  '⇦ Volver al panel': '⇦ Back to the panel',
  '💾 Guardar': '💾 Save',
  '✕ Salir': '✕ Exit',
  'Nombre del proyecto': 'Project name',
  'Tu nombre': 'Your name',
  'Tu nombre (va en el archivo)': 'Your name (goes in the file)',
  'Se guarda solo': 'Saves itself',
  'Descargar el SVG listo para la Cricut o la láser': 'Download the SVG ready for the Cricut or the laser',
  'Guardar el proyecto en tu computadora': 'Save the project to your computer',
  'Volver al inicio': 'Back to the start',

  // --- portal
  'Diseñá tu sombra, mirala proyectada y cortala.': 'Design your shadow, see it projected and cut it.',
  'Soy estudiante': 'I am a student',
  'Pedile el código a tu docente. Si volvés a entrar con el mismo nombre (aunque sea otro día o desde otra compu), tu diseño vuelve tal cual lo dejaste.': 'Ask your teacher for the code. If you come back with the same name (even another day or from another computer), your design comes back just as you left it.',
  'Tu nombre y apellido': 'Your first and last name',
  'Ej.: Camila Pérez': 'E.g.: Emma Smith',
  '🚀 Entrar a la clase': '🚀 Join the class',
  'Soy docente': 'I am a teacher',
  'Creá una clase y compartí el código. Podés tener varias clases abiertas a la vez y ver los diseños de todos en tiempo real. Las clases quedan guardadas en este navegador para volver a abrirlas otro día.': 'Create a class and share the code. You can keep several classes open at once and watch everyone’s designs in real time. Classes are saved in this browser so you can reopen them another day.',
  'Nombre de la clase nueva': 'Name of the new class',
  'Ej.: 2°B — Sombras': 'E.g.: Grade 7B — Shadows',
  '✨ Crear una clase nueva': '✨ Create a new class',
  'Mis clases': 'My classes',
  'Diseñar por mi cuenta': 'Design on my own',
  'Sin clase ni código: el proyecto se guarda en esta computadora y podés bajarlo como archivo para seguir en otra.': 'No class or code: the project is saved on this computer and you can download it as a file to continue on another.',
  '🎨 Empezar a diseñar': '🎨 Start designing',
  '📂 Abrir un archivo .json': '📂 Open a .json file',
  'Mis proyectos en esta computadora': 'My projects on this computer',
  'Tocá uno para seguir donde lo dejaste. Si era de una clase, intenta volver a conectarse; si la clase está cerrada, igual podés seguir trabajando.': 'Tap one to continue where you left off. If it belonged to a class, it tries to reconnect; if the class is closed, you can still keep working.',
  'Inspirado en <a href="https://k12maker.mit.edu/project/shadow-scenes" target="_blank" rel="noopener">Shadow Scenes</a> (MIT K12 Maker). Todo pasa en el navegador: no hay servidor, la clase vive en la computadora del docente.': 'Inspired by <a href="https://k12maker.mit.edu/project/shadow-scenes" target="_blank" rel="noopener">Shadow Scenes</a> (MIT K12 Maker). Everything happens in the browser: there is no server, the class lives on the teacher’s computer.',

  // --- workspace static text
  'Lienzo': 'Canvas',
  'ver fotos': 'show photos',
  'suma': 'add',
  'resta (agujero)': 'subtract (hole)',
  '<strong>¡Tu lienzo está vacío!</strong>': '<strong>Your canvas is empty!</strong>',
  'Hacé clic en un bloque de la izquierda (o arrastralo hasta acá) para agregar una <b>imagen</b>, un <b>texto</b> o una <b>forma</b>.': 'Click a block on the left (or drag it here) to add an <b>image</b>, a <b>text</b> or a <b>shape</b>.',
  'Soltá acá para agregarlo al lienzo': 'Drop here to add it to the canvas',
  '✂ Pieza': '✂ Piece',
  '🔦 Sombra': '🔦 Shadow',
  '▦ Tapete': '▦ Mat',
  'Capa': 'Layer',
  'Mostrar': 'Show',
  'Modo': 'Mode',
  'Tamaño': 'Size',
  'Giro': 'Turn',
  'Ver las fotos reales (con el fondo quitado) o ya como silueta negra': 'Show the real photos (background removed) or already as a black silhouette',
  'Deshacer (Ctrl+Z)': 'Undo (Ctrl+Z)',
  'Rehacer (Ctrl+Y)': 'Redo (Ctrl+Y)',
  'Alejar': 'Zoom out',
  'Ajustar al lienzo': 'Fit to canvas',
  'Acercar': 'Zoom in',
  'Proyectar la sombra (como la bandera verde)': 'Project the shadow (like the green flag)',
  'Volver a la pieza': 'Back to the piece',
  'La pieza cortada, a tamaño real': 'The cut piece, at real size',
  'La sombra que proyecta con una luz detrás': 'The shadow it casts with a light behind',
  'Cómo va al tapete de la cortadora': 'How it goes on the cutter mat',
  'Escenario chico': 'Small stage',
  'Escenario grande': 'Large stage',
  'Ocultar': 'Hide',
  'Suma: agrega figura (negro)': 'Add: makes figure (black)',
  'Resta: hace un agujero (rojo)': 'Subtract: makes a hole (red)',
  'Ancho en mm': 'Width in mm',
  'Ajustes de la pieza (tamaño, tipo, espejo)': 'Piece settings (size, type, mirror)',
  'Subir una foto o dibujo': 'Upload a photo or drawing',
  'Sacar una foto con la cámara': 'Take a photo with the camera',
  'Escribir un texto': 'Write a text',
  'Agregar una forma': 'Add a shape',
  'Agregar al lienzo': 'Add to the canvas',

  // --- tutorial
  '🔦 ¿Cómo se hace una sombra recortada?': '🔦 How do you make a cut-out shadow?',
  'Armá tu diseño en el lienzo': 'Build your design on the canvas',
  'Hacé clic en los bloques de la izquierda: subí una <b>foto</b> o un dibujo (le sacamos el fondo), escribí tu <b>nombre</b> y agregá <b>formas</b>. Movelos, agrandalos y giralos con el mouse.': 'Click the blocks on the left: upload a <b>photo</b> or a drawing (we remove the background), write your <b>name</b> and add <b>shapes</b>. Move, resize and rotate them with the mouse.',
  'Negro suma, rojo resta': 'Black adds, red subtracts',
  'Todo lo <b>negro</b> se corta como una pieza. Si ponés una capa en modo <b>− Resta</b> (queda roja) hace un <b>agujero</b>, y por ahí pasa la luz.': 'Everything <b>black</b> is cut as one piece. If you set a layer to <b>− Subtract</b> mode (it turns red) it makes a <b>hole</b>, and light goes through it.',
  'Mirá el escenario': 'Look at the stage',
  'A la derecha ves la <b>pieza</b> a tamaño real y sus medidas. Apretá la <b>bandera</b> para ver cómo se proyecta la <b>sombra</b> con una luz. Movés el mouse por el escenario y la luz se mueve.': 'On the right you see the <b>piece</b> at real size with its measurements. Press the <b>flag</b> to see how the <b>shadow</b> is cast with a light. Move the mouse over the stage and the light moves.',
  'Descargá y cortá': 'Download and cut',
  'Cuando te guste, tocá <b>✂ SVG</b>. Ese archivo se carga en la Cricut (Design Space → Upload) o en la láser. Cuidado con las piezas sueltas y las letras finitas: el tapete te avisa.': 'When you like it, tap <b>✂ SVG</b>. That file loads into the Cricut (Design Space → Upload) or the laser cutter. Watch out for loose pieces and thin letters: the mat warns you.',
  '<b>Trucos:</b> <kbd>Supr</kbd> borra la capa · <kbd>Ctrl+Z</kbd> deshace · <kbd>Ctrl+D</kbd> duplica · flechas mueven de a poquito · podés <b>arrastrar</b> una foto desde tu escritorio directo al lienzo o <b>pegarla</b> con <kbd>Ctrl+V</kbd>.': '<b>Tricks:</b> <kbd>Del</kbd> deletes the layer · <kbd>Ctrl+Z</kbd> undoes · <kbd>Ctrl+D</kbd> duplicates · arrow keys nudge · you can <b>drag</b> a photo from your desktop straight onto the canvas or <b>paste</b> it with <kbd>Ctrl+V</kbd>.',
  'Tu proyecto se guarda solo en este navegador. Si estás en una clase, también le llega al docente en tiempo real. Para seguir en casa, bajalo con <b>💾 Guardar</b> y abrilo desde el inicio.': 'Your project saves itself in this browser. If you are in a class, it also reaches the teacher in real time. To continue at home, download it with <b>💾 Save</b> and open it from the start screen.',
  '¡A diseñar!': 'Let’s design!',
  '📷 Sacá una foto': '📷 Take a photo',
  'Parate frente a una pared lisa y clara (o una cartulina) para que el fondo se quite fácil. ¡Probá una pose con brazos y piernas bien separados!': 'Stand in front of a plain, light wall (or a poster board) so the background is easy to remove. Try a pose with arms and legs wide apart!',
  '📸 Capturar': '📸 Capture',
  '🔄 Otra cámara': '🔄 Other camera',
  'Cambiar de cámara': 'Switch camera',
  '⭐ Elegí una forma': '⭐ Pick a shape',

  // --- model names (render.js)
  'Bangers (cómic)': 'Bangers (comic)',
  'Bebas Neue (condensada)': 'Bebas Neue (condensed)',
  'Fredoka (redonda)': 'Fredoka (rounded)',
  'Lobster (cursiva)': 'Lobster (script)',
  'Pacifico (manuscrita)': 'Pacifico (handwritten)',
  'Luckiest Guy (gorda)': 'Luckiest Guy (fat)',
  'Abril Fatface (serif)': 'Abril Fatface (serif)',
  'Permanent Marker (marcador)': 'Permanent Marker (marker)',
  'Press Start 2P (pixel)': 'Press Start 2P (pixel)',
  'Arial (del sistema)': 'Arial (system)',
  'Georgia (del sistema)': 'Georgia (system)',
  'Impact (del sistema)': 'Impact (system)',
  'Rectángulo': 'Rectangle',
  'Rectángulo redondeado': 'Rounded rectangle',
  'Círculo / elipse': 'Circle / ellipse',
  'Triángulo': 'Triangle',
  'Estrella': 'Star',
  'Corazón': 'Heart',
  'Luna': 'Moon',
  'Hexágono': 'Hexagon',
  'Flecha': 'Arrow',
  'Anillo': 'Ring',
  'Puente (tira fina)': 'Bridge (thin strip)',
  'Nube': 'Cloud',
  'Rayo': 'Lightning',
  'Gota': 'Drop',
  'Silueta suelta': 'Loose silhouette',
  'Silueta con base': 'Silhouette with base',
  'Silueta con marco': 'Silhouette with frame',
  'Placa calada (ventana)': 'Cut-out plate (window)',
  'Imagen': 'Image',
  'Forma': 'Shape',
  'Sólo lo que dibujás. Ideal para pegar en acetato o en la pared.': 'Only what you draw. Great for sticking on acetate or on the wall.',
  'Le agrega una base rectangular abajo para pararla en una ranura o pegarla a un soporte.': 'Adds a rectangular base at the bottom to stand it in a slot or glue it to a holder.',
  'Un marco alrededor: lo que toca el marco queda unido en una sola pieza.': 'A frame all around: whatever touches the frame stays joined as one piece.',
  'Una placa entera donde tu diseño es el hueco: la luz pasa por el dibujo. Los pedazos que quedan sueltos adentro se caen.': 'A whole plate where your design is the hole: light goes through the drawing. Loose bits inside fall out.',
  '10 × 10 cm': '10 × 10 cm',
  '12 × 12 cm': '12 × 12 cm',
  '15 × 15 cm': '15 × 15 cm',
  '20 × 15 cm': '20 × 15 cm',
  '20 × 20 cm': '20 × 20 cm',
  'A5 (14,8 × 21 cm)': 'A5 (14.8 × 21 cm)',
  'Tapete entero (29 × 29 cm)': 'Whole mat (29 × 29 cm)'
};
